/**
 * Types for the LLM-generated governance analysis of a model.
 *
 * This is the structured output of the auditor-mode analysis: 11 sections
 * matching the governance audit framework, plus a confidence score and
 * top-level findings. The analysis is generated by an LLM but stored as
 * structured data so the UI and PDF can render it consistently.
 */

export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'UNKNOWN';

/** A single risk entry with severity and justification */
export interface RiskFinding {
  /** Short title (e.g., "Hallucination", "Prompt injection") */
  title: string;
  /** Severity rating */
  level: RiskLevel;
  /** Plain-language justification */
  justification: string;
}

/** A gap or unknown — something the auditor couldn't verify */
export interface OpenGap {
  /** Short title (e.g., "Training data composition") */
  title: string;
  /** Why this matters for governance */
  governanceRisk: string;
}

/**
 * The complete 11-section governance analysis.
 * Each section can be a string OR explicitly null to mark "Not assessed."
 * Empty strings are treated as UNKNOWN for display purposes.
 */
export interface GovernanceAnalysis {
  // ── Top-level summary ────────────────────────────────────────
  /** 0-100 confidence in the overall assessment */
  confidenceScore: number;
  /** One-sentence summary of the auditor's verdict */
  summary: string;
  /** Top 3-5 strengths (concrete, evidenced) */
  strengths: string[];
  /** Top 3-5 concerns (concrete, evidenced) */
  concerns: string[];
  /** Top 3-5 recommendations for safe deployment */
  recommendations: string[];

  // ── 11 sections from the user's governance prompt ────────────
  /** §1 Intended Use: primary uses, prohibited uses, high-risk domains */
  intendedUse: {
    primaryUseCases: string;
    prohibitedUseCases: string;
    highRiskDomains: string;
  };

  /** §2 User & Stakeholder Impact */
  userImpact: {
    endUsers: string;
    potentiallyHarmed: string;
    harmScenarios: string;
  };

  /** §3 Risk Assessment — structured list with severity ratings */
  riskAssessment: {
    hallucination: RiskFinding;
    bias: RiskFinding;
    security: RiskFinding;
    misuse: RiskFinding;
  };

  /** §4 Performance & Evaluation */
  performance: {
    knownBenchmarks: string;
    domainPerformance: string;
    failureCases: string;
    confidenceCalibration: string;
  };

  /** §5 Training Data Overview */
  trainingData: {
    sources: string;
    knownExclusions: string;
    biasSources: string;
    ipCopyrightRisk: string;
  };

  /** §6 Safety & Mitigations */
  safety: {
    contentModeration: string;
    refusalBehavior: string;
    guardrails: string;
    monitoringRecommendations: string;
  };

  /** §7 Limitations */
  limitations: {
    poorPerformanceAreas: string;
    untrustedScenarios: string;
    overconfidencePatterns: string;
  };

  /** §8 Operational Guidance */
  operationalGuidance: {
    requiredHumanInLoop: string;
    safeDeploymentPatterns: string;
    unsafeDeploymentPatterns: string;
  };

  /** §9 Compliance & Governance */
  compliance: {
    frameworkAlignment: string;
    dataHandling: string;
    auditRequirements: string;
  };

  /** §10 Versioning & Change Log */
  versioning: {
    changesFromPriorVersions: string;
    riskImplications: string;
  };

  /** §11 Open Gaps — explicit list of unknowns */
  openGaps: OpenGap[];

  // ── Metadata ─────────────────────────────────────────────────
  /** ISO timestamp of when this analysis was generated */
  generatedAt: string;
  /** LLM model used to generate this */
  generatedBy: string;
}

/** Result of a generation attempt */
export interface GovernanceAnalysisResult {
  analysis?: GovernanceAnalysis;
  error?: string;
  /** True if the LLM was unavailable and we returned a fallback */
  fallback?: boolean;
}
