import type { ModelFormData } from '@/types/model';

export const seedModels: ModelFormData[] = [
  {
    name: 'GPT-4o',
    provider: 'openai',
    modelType: 'multimodal',
    version: '2024-08-06',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'OpenAI flagship multimodal model. Text, image, and audio capabilities.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'GPT-4o mini',
    provider: 'openai',
    modelType: 'llm',
    version: '2024-07-18',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Cost-efficient small model for lightweight tasks.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    modelType: 'llm',
    version: 'claude-sonnet-4-20250514',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Anthropic balanced model. Strong reasoning with fast responses.',
    approvedRegions: ['us_only', 'eu_eea', 'uk'],
  },
  {
    name: 'Claude Opus 4',
    provider: 'anthropic',
    modelType: 'llm',
    version: 'claude-opus-4-20250514',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Anthropic most capable model. Extended thinking for complex tasks.',
    approvedRegions: ['us_only', 'eu_eea', 'uk'],
  },
  {
    name: 'Claude Haiku 3.5',
    provider: 'anthropic',
    modelType: 'llm',
    version: 'claude-3-5-haiku-20241022',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Anthropic fastest model. Optimized for high-throughput, low-latency tasks.',
    approvedRegions: ['us_only', 'eu_eea', 'uk'],
  },
  {
    name: 'Llama 3.1 405B',
    provider: 'meta',
    modelType: 'llm',
    version: '3.1',
    status: 'active',
    licenseType: 'open_weights',
    hosting: 'self_hosted',
    description: 'Meta largest open-weights model. Can be self-hosted for data sovereignty.',
    knownLimitations: 'Requires significant compute for self-hosting. No vendor SLA.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Llama 3.1 70B',
    provider: 'meta',
    modelType: 'llm',
    version: '3.1',
    status: 'active',
    licenseType: 'open_weights',
    hosting: 'self_hosted',
    description: 'Meta mid-size open-weights model. Good balance of capability and cost.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    modelType: 'multimodal',
    version: '2.5',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Google flagship multimodal model with extended context.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    modelType: 'multimodal',
    version: '2.5',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Google fast multimodal model. Optimized for speed and cost.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Mistral Large',
    provider: 'mistral',
    modelType: 'llm',
    version: '2',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Mistral flagship model. Strong multilingual and reasoning capabilities.',
    approvedRegions: ['us_only', 'eu_eea', 'uk'],
  },
  {
    name: 'Amazon Nova Pro',
    provider: 'amazon',
    modelType: 'multimodal',
    version: '1.0',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'AWS Bedrock native model. Tight integration with AWS services.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
  {
    name: 'Command R+',
    provider: 'cohere',
    modelType: 'llm',
    version: '1.0',
    status: 'active',
    licenseType: 'proprietary',
    hosting: 'cloud_api',
    description: 'Cohere enterprise RAG-optimized model with citation support.',
    approvedRegions: ['us_only', 'eu_eea', 'uk', 'canada'],
  },
];
